def CreateEndOfFileStuff(inputParams):
    functionString = "/********************************************\n"
    functionString += "Generated by CreateEndOfFileStuff\n"
    functionString += "********************************************/\n"
    functionString += "module_init(" + inputParams.device_name + "_init);\n"
    functionString += "module_exit(" + inputParams.device_name + "_exit);\n"
    functionString += "/* End CreateEndOfFileStuff */\n"
    return functionString