def CreateExitFunction(inputParams):
    functionString =  "/***********************************************\n"
    functionString += "Generated by CreateExitFunction\n"
    functionString += "************************************************/\n"
    functionString += "static void " + inputParams.device_name + "_exit(void) {\n"
    functionString += "  pr_info(\"Audio Logic
    functionString += "  platform_driver_unregister(&" + inputParams.device_name + "_platform);\n"
    if inputParams.device_type == 0:  # SPI device
        functionString += "  if (spi_device) {\n"
        functionString += "    spi_unregister_device(spi_device);\n"
        functionString += "  }\n"
    functionString += "  pr_info(\"Audio Logic
    functionString += "}\n"
    functionString += "/* End CreateExitFunction */\n\n\n"
    return functionString