def CreateAttrReadWriteFuncs(inputParams):
    functionString = "/*****************************************************\n"
    functionString += "Generated by CreateAttrReadWriteFuncs\n"
    functionString += "****************************************************/\n"
    for attr in inputParams.device_attributes:
        functionString += attr.create_read_func(inputParams.device_name)
        functionString += attr.create_write_func(inputParams.device_name)
    functionString += "static ssize_t name_read(struct device *dev, struct device_attribute *attr, char *buf) {\n"
    functionString += "  fe_" + inputParams.device_name + "_dev_t *devp = (fe_" + inputParams.device_name + "_dev_t *)dev_get_drvdata(dev);\n"
    functionString += "  sprintf(buf, \"%s\\n\", devp->name);\n"
    functionString += "  return strlen(buf);\n"
    functionString += "}\n"
    functionString += "/* End of CreateAttrReadWriteFuncs */\n\n\n"
    return functionString