def CreateAttrReadWriteFuncs(inputParams):
    functionString = "/*****************************************************\n"
    functionString += "Generated by CreateAttrReadWriteFuncs\n"
    functionString += "****************************************************/\n"
    if inputParams.device_type == 0:    # SPI device
        functionString += CreateSPIAttrReadWrite(inputParams)
    elif inputParams.device_type == 1:  # I2C device
        functionString += CreateI2CAttrReadWrite(inputParams)
    elif inputParams.device_type == 2:  # FPGA device
        functionString += CreateFPGAAttrReadWrite(inputParams)
    functionString += "/* End of CreateAttrReadWriteFuncs */\n\n\n"
    return functionString


def CreateSPIAttrReadWrite(inputParams):
    functionString = "// SPI Attribute functions\n"
    for i in range(len(inputParams.device_attributes)):
        functionString += "static ssize_t " + inputParams.device_attributes[i] + "_read(struct device *dev, struct device_attribute *attr, char *buf) {\n"
        functionString += "  fe_" + inputParams.device_name + "_dev_t * devp = (fe_" + inputParams.device_name + "_dev_t *)dev_get_drvdata(dev);\n"
        functionString += "  fp_to_string(buf, devp->" + inputParams.device_attributes[i] + ", 16, true, 9);\n"
        functionString += "  strcat2(buf,\"\\n\");\n"
        functionString += "  return strlen(buf);\n"
        functionString += "}\n\n"

        functionString += "static ssize_t " + inputParams.device_attributes[i] + "_write(struct device *dev, struct device_attribute *attr, const char *buf, size_t count) {\n"
        functionString += CreateSPIWriteFunc(inputParams, i)
        functionString += "}\n\n"
    functionString += "static ssize_t name_read(struct device *dev, struct device_attribute *attr, char *buf) {\n"
    functionString += "  // TODO: Fill this in\n"
    functionString += "  return 0;\n"
    functionString += "}\n"
    return functionString


def CreateI2CAttrReadWrite(inputParams):
    functionString = "// I2C Attribute functions\n"
    for i in range(len(inputParams.device_attributes)):
        functionString += "static ssize_t " + inputParams.device_attributes[i] + "_read(struct device *dev, struct device_attribute *attr, char *buf) {\n"
        functionString += "  fe_" + inputParams.device_name + "_dev_t * devp = (fe_" + inputParams.device_name + "_dev_t *)dev_get_drvdata(dev);\n"
        functionString += "  fp_to_string(buf, devp->" + inputParams.device_attributes[i] + ", 16, true, 9);\n"
        functionString += "  strcat2(buf,\"\\n\");\n"
        functionString += "  return strlen(buf);\n"
    
        functionString += "}\n\n"
        functionString += "static ssize_t " + inputParams.device_attributes[i] + "_write(struct device *dev, struct device_attribute *attr, const char *buf, size_t count) {\n"
        functionString += CreateI2CWriteFunc(inputParams, i)
        functionString += "}\n\n"
    functionString += "static ssize_t name_read(struct device *dev, struct device_attribute *attr, char *buf) {\n"
    functionString += "  // TODO: Fill this in\n"
    functionString += "  return 0;\n"
    functionString += "}\n"
    return functionString


def CreateFPGAAttrReadWrite(inputParams):
    functionString = "// FPGA Attribute functions\n"
    for i in range(len(inputParams.device_attributes)):
        functionString += "static ssize_t " + inputParams.device_attributes[i] + "_read(struct device *dev, struct device_attribute *attr, char *buf) {\n"
        functionString += "  fe_" + inputParams.device_name + "_dev_t * devp = (fe_" + inputParams.device_name + "_dev_t *)dev_get_drvdata(dev);\n"
        # TODO: add support for int, bool, etc.
        # TODO: fix parsing of fractional bits; this code currently doesn't return the correct part of the string. we should maybe do the parsing elsewhere and have a field in inputParams for fractional bits
        functionString += "  fp_to_string(buf, devp->" + inputParams.device_attributes[i] + \
            ", " + str(inputParams.attributeDataTypeFraction[i]) + ", " + \
            str(inputParams.attributeDataTypeSigned[i]).lower()+ ", " + \
            str(inputParams.attributeDataTypeWidth[i]) + ");\n"
        functionString += "  strcat2(buf,\"\\n\");\n"
        functionString += "  return strlen(buf);\n"

        functionString += "}\n\n"
        functionString += "static ssize_t " + inputParams.device_attributes[i] + "_write(struct device *dev, struct device_attribute *attr, const char *buf, size_t count) {\n"
        functionString += CreateFPGAWriteFunc(inputParams, i)
        functionString += "}\n\n"
    functionString += "static ssize_t name_read(struct device *dev, struct device_attribute *attr, char *buf) {\n"
    functionString += "  fe_" + inputParams.device_name + "_dev_t *devp = (fe_" + inputParams.device_name + "_dev_t *)dev_get_drvdata(dev);\n"
    functionString += "  sprintf(buf, \"%s\\n\", devp->name);\n"
    functionString += "  return strlen(buf);\n"
    functionString += "}\n"
    return functionString


def CreateSPIWriteFunc(inputParams, i):
    functionString = "  uint32_t tempValue = 0;\n"
    functionString += "  uint8_t volume_level;\n"
    functionString += "  char cmd[" + str(inputParams.attrWriteCommBytes) + "] = {"
    for j in range(inputParams.attrWriteCommBytes):
        functionString += " " + inputParams.attrWriteComm[i][j]
        if j != inputParams.attrWriteCommBytes - 1:
            functionString += ","
    functionString += "};\n"
    functionString += "  char substring[80];\n"
    functionString += "  int substring_count = 0;\n"
    functionString += "  int i;\n"
    functionString += "  fe_" + inputParams.device_name + "_dev_t * devp = (fe_" + inputParams.device_name + "_dev_t *) dev_get_drvdata(dev);\n"
    functionString += "  for (i = 0; i < count; i++) {\n"
    functionString += "    if ((buf[i] != ',') && (buf[i] != ' ') && (buf[i] != '\\0') && (buf[i] != '\\r') && (buf[i] != '\\n')) {\n"
    functionString += "      substring[substring_count] = buf[i];\n"
    functionString += "      substring_count ++;\n"
    functionString += "    }\n"
    functionString += "  }\n"
    functionString += "  substring[substring_count] = '\\0';\n"
    functionString += "  if (buf[0] == '-') {\n"
    functionString += "    for (i = 0; i < 79; i++) {\n"
    functionString += "      substring[i] = substring[i + 1];\n"
    functionString += "    }\n"
    functionString += "  }\n"
    functionString += "  tempValue = set_fixed_num(substring, 28, true);\n"
    functionString += "  volume_level = find_volume_level(tempValue);\n"
    functionString += "  tempValue = decode_volume(volume_level);\n"
    functionString += "  devp->" + inputParams.device_attributes[i] + " = -1 * tempValue;\n"
    functionString += "  cmd[" + str(inputParams.attrWriteCommBytes - 1) + "] = volume_level;\n"
    functionString += "  spi_write(spi_device, &cmd, sizeof(cmd));\n"
    functionString += "  return count;\n"
    return functionString


def CreateI2CWriteFunc(inputParams, i):
    functionString =  "  uint32_t tempValue = 0;\n"
    functionString += "  char substring[80];\n"
    functionString += "  int substring_count = 0;\n"
    functionString += "  int i;\n"
    functionString += "  char cmd[" + str(inputParams.attrWriteCommBytes) + "] = {"
    for j in range(inputParams.attrWriteCommBytes):
        functionString += " " + inputParams.attrWriteComm[i][j]
        if j != inputParams.attrWriteCommBytes - 1:
            functionString += ","
    functionString += "};\n"
    functionString += "  uint8_t code = 0x00;\n"
    functionString += "  fe_" + inputParams.device_name + "_dev_t * devp = (fe_" + inputParams.device_name + \
                      "_dev_t *) dev_get_drvdata(dev);\n"
    functionString += "  for (i = 0; i < count; i++) {\n"
    functionString += "    if ((buf[i] != ',') && (buf[i] != ' ') && (buf[i] != '\\0') && (buf[i] != '\\r') && (buf[i] != '\\n')) {\n"
    functionString += "      substring[substring_count] = buf[i];\n"
    functionString += "      substring_count ++;\n"
    functionString += "    }\n"
    functionString += "  }\n"
    functionString += "  substring[substring_count] = '\\0';\n"
    functionString += "  if (buf[0] == '-') {\n"
    functionString += "    for (i = 0; i < 79; i++) {\n"
    functionString += "      substring[i] = substring[i + 1];\n"
    functionString += "    }\n"
    functionString += "    tempValue = set_fixed_num(substring, 16, true);\n"
    functionString += "    code = find_volume_level(tempValue, 0);\n"
    functionString += "  } else {\n"
    functionString += "    tempValue = set_fixed_num(substring, 16, true);\n"
    functionString += "    code = find_volume_level(tempValue, 1);\n"
    functionString += "  }\n"
    functionString += "  tempValue = decode_volume(code);\n"
    functionString += "  devp->" + inputParams.device_attributes[i] + " = tempValue;\n"
    functionString += "  cmd[" + str(inputParams.attrWriteCommBytes - 1) + "] = code;\n"
    functionString += "  i2c_master_send(" + inputParams.device_name_abbrev + "_i2c_client, &cmd[0], " + str(inputParams.attrWriteCommBytes) + ");\n"
    functionString += "  return count;\n"
    return functionString


def CreateFPGAWriteFunc(inputParams, i):
    functionString =  "  uint32_t tempValue = 0;\n"
    functionString += "  char substring[80];\n"
    functionString += "  int substring_count = 0;\n"
    functionString += "  int i;\n"
    functionString += "  fe_" + inputParams.device_name + "_dev_t *devp = (fe_" + inputParams.device_name + \
                      "_dev_t *)dev_get_drvdata(dev);\n"
    functionString += "  for (i = 0; i < count; i++) {\n"
    functionString += "    if ((buf[i] != ',') && (buf[i] != ' ') && (buf[i] != '\\0') && (buf[i] != '\\r') && (buf[i] != '\\n')) {\n"
    functionString += "      substring[substring_count] = buf[i];\n"
    functionString += "      substring_count ++;\n"
    functionString += "    }\n"
    functionString += "  }\n"
    functionString += "  substring[substring_count] = 0;\n"
    is_signed = inputParams.attributeDataTypeSigned[i]
    functionString += "  tempValue = set_fixed_num(substring, " + \
        str(inputParams.attributeDataTypeFraction[i]) + ", " + (str(is_signed)).lower() + ");\n"
    functionString += "  devp->" + inputParams.device_attributes[i] + " = tempValue;\n"
    functionString += "  iowrite32(devp->" + inputParams.device_attributes[i] + ", (u32 *)devp->regs"
    for j in range(len(inputParams.attributeWriteOffsets[i])):
        functionString += " + " + inputParams.attributeWriteOffsets[i][j]
    functionString += ");\n"
    functionString += "  return count;\n"
    return functionString
