#!/usr/bin/python

# @file CreateCustomFunctions.py
#
#     Python function to create custom functions for AD1939 and TPA613A2 drivers
#
#     @author Trevor Vannoy
#     @date 2019
#     @copyright 2019 Audio Logic
#
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
#     INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
#     PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
#     FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
#     ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#     Trevor Vannoy
#     Audio Logic
#     985 Technology Blvd
#     Bozeman, MT 59718
#     openspeech@flatearthinc.com

def CreateCustomFunctions(inputParams):
    functionString =  "/*********************************************\n"
    functionString += "Generated by CreateCustomFunctions\n"
    functionString += "**********************************************/\n"
    if inputParams.needsVolumeTable:
        file = open("FindVolumeLevelTable", "r")
        functionString += file.read()
    elif inputParams.device_type != 2:  #FPGAS don't need find_volume?
        file = open("FindVolumeLevelNoTable", "r")
        functionString += file.read()
    functionString += "/* End CreateCustomFunctions */\n\n\n"
    return functionString