def CreateRemoveFunction(inputParams):
    functionString =  "/******************************************************\n"
    functionString += "Generated in CreateRemoveFunction\n"
    functionString += "*******************************************************/\n"
    functionString += "static int " + inputParams.device_name + "_remove(struct platform_device *pdev) {\n"
    functionString += "  fe_" + inputParams.device_name + "_dev_t *dev = (fe_" + inputParams.device_name + "_dev_t *)platform_get_drvdata(pdev);\n"
    functionString += "  pr_info(\"" + inputParams.device_name + "_remove enter\\n\");\n"
    functionString += "  device_destroy(cl, dev_num);\n"
    functionString += "  cdev_del(&dev->cdev);\n"
    functionString += "  class_destroy(cl);\n"
    functionString += "  unregister_chrdev_region(dev_num, 2);\n"
    functionString += "  pr_info(\"" + inputParams.device_name + "_remove exit\\n\");\n"
    functionString += "  return 0;\n"
    functionString += "}\n"
    functionString += "/* End CreateRemoveFunction */\n\n\n"
    return functionString